name: lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:          
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
